export const alojamientos = [
  {
    id: 1,
    anfitrion: {
      nombre: 'Juan Pérez',
      email: 'juanperez@mail.com',
      tipo: 'ANFITRION',
    },
    nombre: 'Casa en la playa',
    descripcion: 'Hermosa casa frente al mar con piscina y WiFi.',
    precioPorNoche: 15000,
    moneda: 'PESO_ARG',
    horarioCheckIn: '14:00',
    horarioCheckOut: '11:00',
    direccion: {
      calle: 'Costanera',
      numero: 123,
      ciudad: 'Mar del Plata',
      pais: 'Argentina',
      lat: -38.0055,
      long: -57.5426,
    },
    cantHuespedesMax: 6,
    caracteristicas: ['WIFI', 'PISCINA', 'ESTACIONAMIENTO'],
    reservas: [],
    fotos: [
      {
        descripcion: 'Vista al mar',
        path: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb',
      },
    ],
  },
  {
    id: 2,
    anfitrion: {
      nombre: 'Ana Gómez',
      email: 'anagomez@mail.com',
      tipo: 'ANFITRION',
    },
    nombre: 'Departamento céntrico',
    descripcion: 'Moderno departamento en el centro, ideal para parejas.',
    precioPorNoche: 20000,
    moneda: 'PESO_ARG',
    horarioCheckIn: '15:00',
    horarioCheckOut: '10:00',
    direccion: {
      calle: 'Corrientes',
      numero: 456,
      ciudad: 'Buenos Aires',
      pais: 'Argentina',
      lat: -34.6037,
      long: -58.3816,
    },
    cantHuespedesMax: 2,
    caracteristicas: ['WIFI', 'ESTACIONAMIENTO'],
    reservas: [],
    fotos: [
      {
        descripcion: 'Living moderno',
        path: 'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd',
      },
    ],
  },
  {
    id: 3,
    anfitrion: {
      nombre: 'Carlos Ruiz',
      email: 'carlosruiz@mail.com',
      tipo: 'ANFITRION',
    },
    nombre: 'Cabaña en el bosque',
    descripcion: 'Cabaña rústica rodeada de naturaleza, acepta mascotas.',
    precioPorNoche: 12000,
    moneda: 'PESO_ARG',
    horarioCheckIn: '13:00',
    horarioCheckOut: '12:00',
    direccion: {
      calle: 'Los Pinos',
      numero: 789,
      ciudad: 'Bariloche',
      pais: 'Argentina',
      lat: -41.1335,
      long: -71.3103,
    },
    cantHuespedesMax: 4,
    caracteristicas: ['MASCOTAS_PERMITIDAS', 'ESTACIONAMIENTO'],
    reservas: [],
    fotos: [
      {
        descripcion: 'Cabaña en el bosque',
        path: 'https://images.unsplash.com/photo-1464983953574-0892a716854b',
      },
    ],
  },
]
