export const alojamientos = [
  {
    id: 1,
    anfitrion: {
      nombre: 'Juan Pérez',
      email: 'juanperez@mail.com',
      tipo: 'ANFITRION',
    },
    nombre: 'Casa en la playa',
    descripcion: 'Hermosa casa frente al mar con piscina y WiFi.',
    precioPorNoche: 15000,
    moneda: 'PESO_ARG',
    horarioCheckIn: '14:00',
    horarioCheckOut: '11:00',
    direccion: {
      calle: 'Costanera',
      numero: 123,
      ciudad: 'Mar del Plata',
      pais: 'Argentina',
      lat: -38.0055,
      long: -57.5426,
    },
    cantHuespedesMax: 6,
    caracteristicas: ['WIFI', 'PISCINA', 'ESTACIONAMIENTO'],
    reservas: [
      {
        rangoFechas: {
          fechaInicio: '2025-06-24T03:00:00.000Z',
          fechaFin: '2025-06-30T03:00:00.000Z',
        },
      },
    ],
    fotos: [
      {
        descripcion: 'Vista al mar',
        path: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb',
      },
    ],
  },
  {
    id: 2,
    anfitrion: {
      nombre: 'Ana Gómez',
      email: 'anagomez@mail.com',
      tipo: 'ANFITRION',
    },
    nombre: 'Departamento céntrico',
    descripcion: 'Moderno departamento en el centro, ideal para parejas.',
    precioPorNoche: 20000,
    moneda: 'PESO_ARG',
    horarioCheckIn: '15:00',
    horarioCheckOut: '10:00',
    direccion: {
      calle: 'Corrientes',
      numero: 456,
      ciudad: 'Buenos Aires',
      pais: 'Argentina',
      lat: -34.6037,
      long: -58.3816,
    },
    cantHuespedesMax: 2,
    caracteristicas: ['WIFI', 'ESTACIONAMIENTO'],
    reservas: [],
    fotos: [
      {
        descripcion: 'Living moderno',
        path: 'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd',
      },
    ],
  },
  {
    id: 3,
    anfitrion: {
      nombre: 'Carlos Ruiz',
      email: 'carlosruiz@mail.com',
      tipo: 'ANFITRION',
    },
    nombre: 'Cabaña en el bosque',
    descripcion: 'Cabaña rústica rodeada de naturaleza, acepta mascotas.',
    precioPorNoche: 12000,
    moneda: 'PESO_ARG',
    horarioCheckIn: '13:00',
    horarioCheckOut: '12:00',
    direccion: {
      calle: 'Los Pinos',
      numero: 789,
      ciudad: 'Bariloche',
      pais: 'Argentina',
      lat: -41.1335,
      long: -71.3103,
    },
    cantHuespedesMax: 4,
    caracteristicas: ['MASCOTAS_PERMITIDAS', 'ESTACIONAMIENTO'],
    reservas: [],
    fotos: [
      {
        descripcion: 'Cabaña en el bosque',
        path: 'https://images.unsplash.com/photo-1464983953574-0892a716854b',
      },
    ],
  },
  {
    id: 4,
    anfitrion: {
      nombre: 'Lucía Fernández',
      email: 'luciafernandez@mail.com',
      tipo: 'ANFITRION',
    },
    nombre: 'Loft moderno',
    descripcion: 'Loft luminoso con terraza privada y parrilla.',
    precioPorNoche: 18000,
    moneda: 'PESO_ARG',
    horarioCheckIn: '16:00',
    horarioCheckOut: '11:00',
    direccion: {
      calle: 'Santa Fe',
      numero: 321,
      ciudad: 'Córdoba',
      pais: 'Argentina',
      lat: -31.4201,
      long: -64.1888,
    },
    cantHuespedesMax: 3,
    caracteristicas: ['WIFI', 'PARRILLA', 'TERRAZA'],
    reservas: [],
    fotos: [
      {
        descripcion: 'Terraza con parrilla',
        path: 'https://images.unsplash.com/photo-1507089947368-19c1da9775ae',
      },
    ],
  },
  {
    id: 5,
    anfitrion: {
      nombre: 'Martín López',
      email: 'martinlopez@mail.com',
      tipo: 'ANFITRION',
    },
    nombre: 'Casa familiar',
    descripcion: 'Amplia casa ideal para familias, con jardín y juegos.',
    precioPorNoche: 22000,
    moneda: 'PESO_ARG',
    horarioCheckIn: '14:00',
    horarioCheckOut: '10:00',
    direccion: {
      calle: 'Belgrano',
      numero: 654,
      ciudad: 'Rosario',
      pais: 'Argentina',
      lat: -32.9442,
      long: -60.6505,
    },
    cantHuespedesMax: 7,
    caracteristicas: ['JARDIN', 'JUEGOS_PARA_NIÑOS', 'ESTACIONAMIENTO'],
    reservas: [],
    fotos: [
      {
        descripcion: 'Jardín amplio',
        path: 'https://images.unsplash.com/photo-1465101046530-73398c7f28ca',
      },
    ],
  },
  {
    id: 6,
    anfitrion: {
      nombre: 'Sofía Martínez',
      email: 'sofiamartinez@mail.com',
      tipo: 'ANFITRION',
    },
    nombre: 'Monoambiente acogedor',
    descripcion: 'Pequeño monoambiente cerca de la universidad.',
    precioPorNoche: 9000,
    moneda: 'PESO_ARG',
    horarioCheckIn: '12:00',
    horarioCheckOut: '10:00',
    direccion: {
      calle: 'San Martín',
      numero: 111,
      ciudad: 'La Plata',
      pais: 'Argentina',
      lat: -34.9214,
      long: -57.9544,
    },
    cantHuespedesMax: 2,
    caracteristicas: ['WIFI', 'CALEFACCION'],
    reservas: [],
    fotos: [
      {
        descripcion: 'Espacio funcional',
        path: 'https://images.unsplash.com/photo-1519125323398-675f0ddb6308',
      },
    ],
  },
  {
    id: 7,
    anfitrion: {
      nombre: 'Diego Torres',
      email: 'diegotorres@mail.com',
      tipo: 'ANFITRION',
    },
    nombre: 'Dúplex con pileta',
    descripcion: 'Dúplex moderno con pileta y cochera privada.',
    precioPorNoche: 25000,
    moneda: 'PESO_ARG',
    horarioCheckIn: '15:00',
    horarioCheckOut: '12:00',
    direccion: {
      calle: 'Mitre',
      numero: 222,
      ciudad: 'Mendoza',
      pais: 'Argentina',
      lat: -32.8895,
      long: -68.8458,
    },
    cantHuespedesMax: 5,
    caracteristicas: ['PISCINA', 'COCHERA', 'WIFI'],
    reservas: [],
    fotos: [
      {
        descripcion: 'Pileta y jardín',
        path: 'https://images.unsplash.com/photo-1505691938895-1758d7feb511',
      },
    ],
  },
  {
    id: 8,
    anfitrion: {
      nombre: 'Valentina Castro',
      email: 'valentinacastro@mail.com',
      tipo: 'ANFITRION',
    },
    nombre: 'Habitación privada',
    descripcion: 'Habitación privada en casa compartida, desayuno incluido.',
    precioPorNoche: 8000,
    moneda: 'PESO_ARG',
    horarioCheckIn: '13:00',
    horarioCheckOut: '11:00',
    direccion: {
      calle: 'Rivadavia',
      numero: 789,
      ciudad: 'Salta',
      pais: 'Argentina',
      lat: -24.7821,
      long: -65.4232,
    },
    cantHuespedesMax: 1,
    caracteristicas: ['DESAYUNO', 'WIFI'],
    reservas: [],
    fotos: [
      {
        descripcion: 'Habitación luminosa',
        path: 'https://decormatters-blog-uploads.s3.amazonaws.com/365407283_614619890658463_4618795059015039771_n_c6362e5ece.jpg',
      },
    ],
  },
]
